server:
  address: 127.0.0.1
  port: 9001
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/em_bds
    username: zmax
    password: 123
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: mx.sonder.scrbkend.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  is-sign-up: true
  secret: SpringBoot-BitScreen-XVFS-LK8S-96PG-VS9A
  expire: 21600

py-api:
  user-agent: data-analysis-core-api
  token: core-1.0.0
