spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:sqlite:D:/GraduationDesign/All-Good-Things/scrbkend/app.db
    driver-class-name: org.sqlite.JDBC
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: mx.sonder.scrbkend.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: SpringBoot-BitScreen-XVFS-LK8S-96PG-VS9A
  # expire: 21600
  expire: 21600
